# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-04 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20180404_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='\u0418\u043c\u044f'),
            preserve_default=False,
        ),
    ]
