# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-06 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20180404_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingTabTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.Flatpage', verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': '\u0412\u043a\u043b\u0430\u0434\u043a\u0430 \u043d\u0430 \u043b\u0435\u043d\u0434\u0438\u043d\u0433\u0435 (\u041f\u0435\u0440\u0435\u0432\u043e\u0434\u044b)',
                'verbose_name_plural': '\u0412\u043a\u043b\u0430\u0434\u043a\u0438 \u043d\u0430 \u043b\u0435\u043d\u0434\u0438\u043d\u0433\u0435 (\u041f\u0435\u0440\u0435\u0432\u043e\u0434\u044b)',
            },
        ),
        migrations.AlterModelOptions(
            name='landingtab',
            options={'ordering': ('order',), 'verbose_name': '\u0412\u043a\u043b\u0430\u0434\u043a\u0430 \u043d\u0430 \u043b\u0435\u043d\u0434\u0438\u043d\u0433\u0435 (\u041a\u0440\u0435\u0434\u0438\u0442\u044b)', 'verbose_name_plural': '\u0412\u043a\u043b\u0430\u0434\u043a\u0438 \u043d\u0430 \u043b\u0435\u043d\u0434\u0438\u043d\u0433\u0435 (\u041a\u0440\u0435\u0434\u0438\u0442\u044b)'},
        ),
        migrations.AlterField(
            model_name='landingtab',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.Flatpage', verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430'),
        ),
    ]
