# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-06 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20180406_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingTabExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.Flatpage', verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': '\u0412\u0435\u0440\u0445\u043d\u0435\u0435 \u043c\u0435\u043d\u044e',
                'verbose_name_plural': '\u0412\u0435\u0440\u0445\u043d\u0435\u0435 \u043c\u0435\u043d\u044e',
            },
        ),
        migrations.CreateModel(
            name='MainCreditBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('credit', '\u041a\u0440\u0435\u0434\u0438\u0442'), ('transfers', '\u041f\u0435\u0440\u0435\u0432\u043e\u0434\u044b')], default='credit', max_length=20, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u043b\u0435\u043d\u0434\u0438\u043d\u0433\u0430')),
                ('title', models.CharField(max_length=250, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('main_image', models.ImageField(upload_to='images/', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('extra_image', models.ImageField(upload_to='images/', verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f')),
                ('button1', models.CharField(max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0435\u0440\u0432\u043e\u0439 \u043a\u043d\u043e\u043f\u043a\u0438')),
                ('button2', models.CharField(max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0432\u0442\u043e\u0440\u043e\u0439 \u043a\u043d\u043e\u043f\u043a\u0438')),
            ],
            options={
                'verbose_name': '\u041e\u0441\u043d\u043e\u0432\u043d\u043e\u0439 \u0431\u043b\u043e\u043a',
                'verbose_name_plural': '\u041e\u0441\u043d\u043e\u0432\u043d\u043e\u0439 \u0431\u043b\u043e\u043a',
            },
        ),
    ]
