# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-06 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_landingtabextra_maincreditblock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainCreditBlock',
            new_name='MainBlock',
        ),
    ]
