# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-10 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_footermenublock1credit_footermenublock1transfer_footermenublock2credit_footermenublock2transfer_foot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('credit', '\u041a\u0440\u0435\u0434\u0438\u0442'), ('transfers', '\u041f\u0435\u0440\u0435\u0432\u043e\u0434\u044b')], default='credit', max_length=20, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430')),
                ('icon', models.ImageField(upload_to='images/', verbose_name='\u0418\u043a\u043e\u043d\u043a\u0430')),
                ('content', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('order', models.IntegerField(default=0, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a')),
                ('draft', models.BooleanField(default=False, verbose_name='\u0427\u0435\u0440\u043d\u043e\u0432\u0438\u043a')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u0435\u0438\u043c\u0443\u0449\u0435\u0441\u0442\u0432\u043e',
                'verbose_name_plural': '\u041f\u0440\u0435\u0438\u043c\u0443\u0449\u0435\u0441\u0442\u0432\u0430',
            },
        ),
    ]
